### ISSUE TITLE
churn dataset not available

### ISSUE THREAD

**Issue by mbao01** [pauloreis-ds/projects#1]
Hi, would you like contribution on this. Also can you add a `churn.csv` to this repo so that the notebook can be reproduced?
If the file is large, maybe a link to download it would be great.

Thanks

**Comment by pauloreis-ds** [comment]
Dataset: https://www.kaggle.com/mervetorkan/churndataset

A Brazilian Data Scientist created a context so we could use this data while thinking as a problem solver. When I'm done I'll make everything available. But, since I have already translated it, I'll put it here in case you want to try solving that challenge. Have a good day!




TopBank is a large banking services company. It operates mainly in European countries offering financial products, from bank accounts to investments, including some types of insurance and investment products.

The company's business model is a service type, that is, it sells banking services to its customers through physical agencies and an online portal.

The company's main product is a bank account, in which the customer can deposit his salary, make withdrawals, deposits and transfer to other accounts. This bank account has no cost to the customer and is valid for 12 months, that is, the customer needs to renew the contract of that account to continue using it for the next 12 months.

According to the TopBank Analytics team, each customer who has this bank account returns a monetary value of 15% of the value of their estimated salary, if it is less than the average and 20% if this salary is higher than the average, during the current period of your account. This value is calculated annually.

For example, if a customer's monthly salary is R$ 1,000.00 and the average of all bank wages is R$ 800. The company, therefore, invoices R$ 200 annually with this client. If this customer has been in the bank for 10 years, the company has already earned R$ 2,000.00 from its transactions and account usage.

In recent months, the Analytics team realized that the rate of customers canceling their accounts and leaving the bank reached unprecedented numbers in the company. Concerned about the increase in this rate, the team devised an action plan to reduce the rate of customer evasion.

Concerned about the drop in this metric, TopBank's Analytics team hired you as a Data Science consultant to create an action plan, with the objective of reducing customer evasion, that is, preventing the customer from canceling his contract and not renew it for another 12 months. This evasion, in business metrics, is known as Churn.

In general, Churn is a metric that indicates the number of customers who have canceled the contract or have stopped buying your product within a certain period of time. For example, customers who canceled the service contract or after it expired, did not renew it, they are considered churn customers.

Another example would be customers who have not made a purchase for more than 60 days. These customers can be considered churn customers until a purchase is made. The 60-day period is completely arbitrary and varies between companies.

The challenge
As a Data Science Consultant, you need to create an action plan to decrease the number of churn customers and show the financial return on your solution.

At the end of your consultancy, you need to deliver to the TopBank CEO a model in production, which will receive a customer base via API and return that same base scored, that is, one more column with the probability of each customer entering into churn.

In addition, you will need to provide a report reporting the performance of your model and the financial impact of your solution. Questions that the CEO and the Analytics team would like to see in their report:

What is TopBank's current Churn rate? How does it vary monthly?
What is the model's performance in classifying customers as churns?
What is the expected return, in terms of revenue, if the company uses your model to avoid churn from customers?

A possible action to prevent the customer from churning is to offer a discount coupon, or some other financial incentive for him to renew his contract for another 12 months.

Which customers would you give the financial incentive to and what would that amount be, in order to maximize ROI (Return on Investment). Recalling that the sum of incentives cannot exceed R$ 10,000.00
